import type { ReactNode } from 'react';
import Image from 'next/image';
import { ArrowUpRight, Play, Phone } from 'lucide-react';
import { Header } from '@/components/Header';
import { FadeIn } from '@/components/Motion';
import { Gallery } from '@/components/Gallery';
import { designs, grades, reviews, services, stats } from '@/data/site';
const Section=({id,children,className=''}:{id?:string;children: ReactNode;className?:string})=><section id={id} className={`container-av py-20 sm:py-28 ${className}`}>{children}</section>;
export default function Home(){return <main id="top"><Header/><Section className="grid min-h-screen items-center gap-10 pt-36 lg:grid-cols-[1.05fr_.95fr]"><FadeIn><p className="mb-6 text-sm font-bold uppercase tracking-[.3em] text-avred">Барнаул<br/>Новосибирск</p><h1 className="max-w-5xl text-5xl font-black leading-[.9] tracking-[-.06em] sm:text-7xl lg:text-8xl">Выпускные альбомы,<br/>которые будут пересматривать спустя годы</h1><p className="mt-8 max-w-xl text-xl text-black/60">Полный цикл работы: от фотосессии до печати и доставки готовых альбомов.</p><div className="mt-10 flex flex-col gap-3 sm:flex-row"><a className="focus-ring rounded-full bg-black px-7 py-4 text-white hover:bg-avred" href="#albums">Смотреть альбомы</a><a className="focus-ring rounded-full border border-black px-7 py-4 hover:bg-white" href="#contacts">Рассчитать стоимость</a></div></FadeIn><FadeIn className="relative h-[520px] overflow-hidden rounded-[3rem] bg-gray-200"><Image src="/photos/hero.svg" alt="Выпускник с альбомом AVBOOK" fill priority className="object-cover grayscale"/><div className="absolute bottom-6 left-6 rounded-2xl bg-white/90 p-5 text-3xl font-black">AVBOOK</div></FadeIn></Section>
<Section><div className="grid gap-8 border-y border-black/10 py-16 lg:grid-cols-2"><h2 className="text-4xl font-black tracking-[-.04em] sm:text-7xl">Мы создаём не альбомы.<br/>Мы сохраняем историю класса</h2><p className="max-w-lg self-end text-xl text-black/60">Каждый класс — это целая история. Дружба, эмоции, достижения и важные моменты, которые хочется сохранить на всю жизнь.</p></div></Section>
<Section id="process"><div className="relative h-[560px] overflow-hidden rounded-[3rem]"><Image src="/photos/process.svg" alt="Процесс съёмки AVBOOK" fill className="object-cover grayscale"/><div className="absolute inset-0 bg-black/25"/><h2 className="absolute bottom-8 left-8 text-5xl font-black leading-none text-white sm:text-8xl">Один день.<br/>Останется<br/>на всю жизнь</h2><div className="absolute right-8 top-8 grid size-24 place-items-center rounded-full bg-white text-black"><Play fill="currentColor"/></div></div></Section>
<Section id="albums"><h2 className="mb-10 text-5xl font-black tracking-[-.05em]">Альбомы по классам</h2><div className="flex snap-x gap-5 overflow-x-auto pb-4 lg:grid lg:grid-cols-3 lg:overflow-visible">{grades.map(g=><article key={g.title} className="min-w-[82vw] snap-start rounded-[2.5rem] bg-white p-4 sm:min-w-[420px] lg:min-w-0"><div className="relative h-80 overflow-hidden rounded-[2rem]"><Image src={g.image} alt={g.title} fill className="object-cover grayscale"/></div><div className="flex items-end justify-between p-4"><div><h3 className="text-4xl font-black">{g.title}</h3><p className="mt-3 text-black/60">{g.text}</p></div><button className="grid size-14 place-items-center rounded-full bg-black text-white hover:bg-avred"><ArrowUpRight/></button></div></article>)}</div></Section>
<section className="bg-black py-24 text-white"><div className="container-av"><h2 className="mb-10 text-5xl font-black tracking-[-.05em]">Популярные дизайны</h2><div className="flex gap-5 overflow-x-auto pb-4 lg:grid lg:grid-cols-5">{designs.map(d=><article className="min-w-[260px] rounded-[2rem] border border-white/10 bg-white/5 p-4" key={d.title}><div className="relative h-64 overflow-hidden rounded-[1.5rem]"><Image src={d.image} alt={d.title} fill className="object-cover grayscale"/></div><h3 className="mt-5 text-2xl font-black">{d.title}</h3><p className="mt-2 text-sm text-white/60">{d.text}</p></article>)}</div></div></section>
<Section><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{stats.map(s=><FadeIn key={s.label} className="rounded-[2rem] bg-white p-8"><div className="text-6xl font-black tracking-[-.06em]">{s.value}</div><p className="mt-3 text-black/60">{s.label}</p></FadeIn>)}</div></Section>
<section className="bg-[#111] py-24 text-white"><div className="container-av grid gap-10 lg:grid-cols-2"><div><h2 className="mb-8 text-5xl font-black tracking-[-.05em]">Организация полностью на нас</h2><div className="grid gap-4 sm:grid-cols-2">{services.map(({icon:Icon,...s})=><div key={s.title} className="rounded-3xl bg-white/5 p-6"><Icon className="text-avred"/><h3 className="mt-4 text-2xl font-bold">{s.title}</h3><p className="mt-2 text-white/60">{s.text}</p></div>)}</div></div><div className="relative min-h-[520px] overflow-hidden rounded-[3rem]"><Image src="/photos/stack.svg" alt="Стопка выпускных альбомов" fill className="object-cover grayscale"/></div></div></section>
<Section id="works"><h2 className="mb-4 text-5xl font-black tracking-[-.05em]">Наши работы</h2><p className="mb-10 text-black/60">Альбомы · Портреты · Групповые фотографии · Развороты</p><Gallery/></Section>
<Section id="reviews"><h2 className="mb-10 text-5xl font-black tracking-[-.05em]">Отзывы родителей</h2><div className="grid gap-5 lg:grid-cols-4">{reviews.map(r=><article key={r.name} className="rounded-[2rem] bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><Image src={r.avatar} alt={r.name} width={54} height={54} className="rounded-full grayscale"/><div><h3 className="font-bold">{r.name}</h3><p className="text-sm text-black/50">{r.role}</p></div></div><p className="mt-5 text-black/70">{r.text}</p><p className="mt-4 text-right text-sm text-black/40">{r.time}</p></article>)}</div></Section>
<section id="contacts" className="bg-black py-24 text-white"><div className="container-av grid gap-10 lg:grid-cols-2"><div><h2 className="text-5xl font-black tracking-[-.05em] sm:text-7xl">Готовы создать лучший выпускной альбом?</h2><p className="mt-6 max-w-xl text-xl text-white/60">Оставьте заявку и получите каталог альбомов и расчёт стоимости для вашего класса.</p><a className="mt-10 inline-block rounded-full bg-white px-8 py-4 font-bold text-black hover:bg-avred hover:text-white" href="https://wa.me/79132100120">Получить каталог</a></div><div className="self-end rounded-[2rem] border border-white/10 p-8"><Phone className="text-avred"/><a className="mt-4 block text-4xl font-black" href="tel:+79132100120">+7 (913) 210-01-20</a><div className="mt-8 flex gap-4 text-white/70"><a href="#">WhatsApp</a><a href="#">ВКонтакте</a><a href="#">Telegram</a></div></div></div></section>
<footer className="container-av flex flex-col gap-4 py-10 text-sm text-black/55 md:flex-row md:items-center md:justify-between"><b className="text-xl text-black">AVBOOK</b><span>Агентство выпускных альбомов</span><span>Барнаул и Новосибирск</span><a href="#">Политика конфиденциальности</a><span>2026</span></footer></main>}
